DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_13325";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_14009";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_14013";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_17384";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_18007";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_18104";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_18228";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_3843";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_44508";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_7433";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_fluxograma_8380";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_13325";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_14009";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_14013";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_17384";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_18007";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_18104";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_18228";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_3843";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_44508";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_7433";
DROP MATERIALIZED VIEW IF EXISTS "mat_view_corregedoria_8380";

DROP TABLE IF EXISTS "test_movimentos_13325";
DROP TABLE IF EXISTS "test_movimentos_14009";
DROP TABLE IF EXISTS "test_movimentos_14013";
DROP TABLE IF EXISTS "test_movimentos_17384";
DROP TABLE IF EXISTS "test_movimentos_18007";
DROP TABLE IF EXISTS "test_movimentos_18104";
DROP TABLE IF EXISTS "test_movimentos_18228";
DROP TABLE IF EXISTS "test_movimentos_3843";
DROP TABLE IF EXISTS "test_movimentos_44508";
DROP TABLE IF EXISTS "test_movimentos_7433";
DROP TABLE IF EXISTS "test_movimentos_8380";
DROP TABLE IF EXISTS "test_processos_13325";
DROP TABLE IF EXISTS "test_processos_14009";
DROP TABLE IF EXISTS "test_processos_14013";
DROP TABLE IF EXISTS "test_processos_17384";
DROP TABLE IF EXISTS "test_processos_18007";
DROP TABLE IF EXISTS "test_processos_18104";
DROP TABLE IF EXISTS "test_processos_18228";
DROP TABLE IF EXISTS "test_processos_3843";
DROP TABLE IF EXISTS "test_processos_44508";
DROP TABLE IF EXISTS "test_processos_7433";
DROP TABLE IF EXISTS "test_processos_8380";
DROP TABLE IF EXISTS "test_processos_row_count";

DROP TABLE IF EXISTS query_execution_times;
DROP TABLE IF EXISTS unidade_storage_size;